version: '3.3'

services: 
  postgres:
    image: timescale/timescaledb:2.6.0-pg14
    ports: 
      - '54320:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes: 
  postgres-data: {}
