{
 "title": "Nerves Weather Tracker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Current Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uva_raw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  uva_raw\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "uvb_raw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  uvb_raw\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  altitude_m\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  pressure_pa\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  temperature_c\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CO2 Levels",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  co2_eq_ppm\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TVOC Levels",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  tvoc_ppb\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  { "title": "Over Time Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  temperature_c\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CO2 Levels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  co2_eq_ppm\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TVOC Levels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  tvoc_ppb\nFROM weather_conditions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}